import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { config as loadEnv } from "dotenv";

// Resolve paths relative to this file rather than process.cwd() so the server works
// regardless of how it's launched (e.g. `npm start --prefix ...` from another dir).
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

loadEnv({ path: resolve(projectRoot, ".env") });

interface ToolSchema {
  description?: string;
  procedureType: "query" | "mutation";
  inputSchema: Record<string, unknown>;
}

// Read at runtime rather than statically importing the JSON: the file is generated by the
// `prestart` codegen step, so it doesn't exist at typecheck time on a fresh clone, and
// readFileSync sidesteps the ESM/CJS json-import-attribute differences.
const schemasPath = resolve(projectRoot, "src/generated/schemas.json");
const proceduresByPath = JSON.parse(readFileSync(schemasPath, "utf-8")) as Record<
  string,
  ToolSchema
>;

// MCP tool names may only contain [A-Za-z0-9_-] (strict clients like VSCode reject dots).
// tRPC procedure paths use dot-notation (e.g. "topic.create"), so map dots to underscores
// for the wire-level tool name and keep the original path for forwarding to tRPC.
const toolEntries = Object.entries(proceduresByPath).map(([path, schema]) => ({
  toolName: path.replace(/\./g, "_"),
  path,
  schema,
}));

const toolNameToPath = new Map(
  toolEntries.map(({ toolName, path }) => [toolName, path] as [string, string]),
);
const tools: Record<string, ToolSchema> = Object.fromEntries(
  toolEntries.map(({ toolName, schema }) => [toolName, schema]),
);

// Default to localhost because this MCP server is intended for local use —
// typical workflow is running the main Ameliorate dev server locally and
// pointing the MCP server at it. Set AMELIORATE_BASE_URL=https://ameliorate.app
// (or another deployment) to override.
const BASE = process.env.AMELIORATE_BASE_URL ?? "http://localhost:3000";
const PAT = process.env.AMELIORATE_PAT;

// eslint-disable-next-line @typescript-eslint/no-deprecated
const server = new Server(
  { name: "ameliorate-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, () => ({
  tools: Object.entries(tools).map(([name, { description, inputSchema }]) => ({
    name,
    description,
    inputSchema,
  })),
}));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params;

  const tool = tools[name];
  const procedurePath = toolNameToPath.get(name);

  if (!tool || !procedurePath) {
    return {
      content: [{ type: "text", text: `Unknown tool: ${name}` }],
      isError: true,
    };
  }

  const headers: Record<string, string> = {
    "content-type": "application/json",
    ...(PAT ? { Authorization: `Bearer ${PAT}` } : {}),
  };

  const queryInput = encodeURIComponent(JSON.stringify({ json: args ?? {} }));
  const url =
    tool.procedureType === "query"
      ? `${BASE}/api/trpc/${procedurePath}?input=${queryInput}` // query-type procedures expect input via query string
      : `${BASE}/api/trpc/${procedurePath}`; // mutation-type procedures expect input via request body

  const res = await fetch(url, {
    method: tool.procedureType === "query" ? "GET" : "POST",
    headers,
    body: tool.procedureType === "query" ? undefined : JSON.stringify({ json: args ?? {} }),
  });

  const text = await res.text();
  return {
    content: [{ type: "text", text }],
    isError: !res.ok,
  };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
