import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { config as loadEnv } from "dotenv";
import { z } from "zod";

// Resolve paths relative to this file rather than process.cwd() so the server works
// regardless of how it's launched (e.g. `npm start --prefix ...` from another dir).
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

loadEnv({ path: resolve(projectRoot, ".env") });

interface ToolSchema {
  description?: string;
  procedureType: "query" | "mutation";
  inputSchema: Record<string, unknown>;
}

// Read at runtime rather than statically importing the JSON: the file is generated by the
// `prestart` codegen step, so it doesn't exist at typecheck time on a fresh clone, and
// readFileSync sidesteps the ESM/CJS json-import-attribute differences.
const schemasPath = resolve(projectRoot, "src/generated/schemas.json");
const proceduresByPath = JSON.parse(readFileSync(schemasPath, "utf-8")) as Record<
  string,
  ToolSchema
>;

// MCP tool names may only contain [A-Za-z0-9_-] (strict clients like VSCode reject dots).
// tRPC procedure paths use dot-notation (e.g. "topic.create"), so map dots to underscores
// for the wire-level tool name and keep the original path for forwarding to tRPC.
const toolEntries = Object.entries(proceduresByPath).map(([path, schema]) => ({
  toolName: path.replace(/\./g, "_"),
  path,
  schema,
}));

const toolNameToPath = new Map(
  toolEntries.map(({ toolName, path }) => [toolName, path] as [string, string]),
);
const tools: Record<string, ToolSchema> = Object.fromEntries(
  toolEntries.map(({ toolName, schema }) => [toolName, schema]),
);

// Default to localhost because this MCP server is intended for local use —
// typical workflow is running the main Ameliorate dev server locally and
// pointing the MCP server at it. Set AMELIORATE_BASE_URL=https://ameliorate.app
// (or another deployment) to override.
const BASE = process.env.AMELIORATE_BASE_URL ?? "http://localhost:3000";

const usersSchema = z.array(
  z.object({ username: z.string(), description: z.string(), pat: z.string() }),
);

function parseRawJson(raw: string): unknown {
  try {
    return JSON.parse(raw);
  } catch (err) {
    console.error("AMELIORATE_USERS is not valid JSON:", (err as Error).message);
    process.exit(1);
  }
}

function parseUsers(): z.infer<typeof usersSchema> {
  const usersString = process.env.AMELIORATE_USERS;
  if (!usersString) {
    console.error("AMELIORATE_USERS is not set. See .env.example for the expected JSON shape.");
    process.exit(1);
  }
  const usersJson = parseRawJson(usersString);
  const result = usersSchema.safeParse(usersJson);
  if (!result.success) {
    console.error("AMELIORATE_USERS failed schema validation:", result.error.message);
    process.exit(1);
  }
  return result.data;
}

const users = parseUsers();
const patByUsername = new Map(users.map((u) => [u.username, u.pat]));
const usernames = users.map((u) => u.username);
const userToActAsDescription = `Which configured user to act as for this call. Options: ${users
  .map((u) => `"${u.username}" (${u.description})`)
  .join("; ")}`;

// eslint-disable-next-line @typescript-eslint/no-deprecated
const server = new Server(
  { name: "ameliorate-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, () => ({
  tools: Object.entries(tools).map(([name, { description, inputSchema }]) => {
    const properties = (inputSchema.properties as Record<string, unknown> | undefined) ?? {};
    const required = (inputSchema.required as string[] | undefined) ?? [];
    const augmentedInputSchema = {
      ...inputSchema,
      properties: {
        ...properties,
        userToActAs: {
          type: "string",
          enum: usernames,
          description: userToActAsDescription,
        },
      },
      required: [...required, "userToActAs"],
    };
    return { name, description, inputSchema: augmentedInputSchema };
  }),
}));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params;

  const tool = tools[name];
  const procedurePath = toolNameToPath.get(name);

  if (!tool || !procedurePath) {
    return {
      content: [{ type: "text", text: `Unknown tool: ${name}` }],
      isError: true,
    };
  }

  const { userToActAs, ...forwardedArgs } = args ?? {};
  const pat = typeof userToActAs === "string" ? patByUsername.get(userToActAs) : undefined;
  if (!pat) {
    return {
      content: [
        {
          type: "text",
          text: `userToActAs is required and must be one of: ${usernames.join(", ")}. Received: ${JSON.stringify(userToActAs)}`,
        },
      ],
      isError: true,
    };
  }

  const headers: Record<string, string> = {
    "content-type": "application/json",
    Authorization: `Bearer ${pat}`,
  };

  const queryInput = encodeURIComponent(JSON.stringify({ json: forwardedArgs }));
  const url =
    tool.procedureType === "query"
      ? `${BASE}/api/trpc/${procedurePath}?input=${queryInput}` // query-type procedures expect input via query string
      : `${BASE}/api/trpc/${procedurePath}`; // mutation-type procedures expect input via request body

  const res = await fetch(url, {
    method: tool.procedureType === "query" ? "GET" : "POST",
    headers,
    body: tool.procedureType === "query" ? undefined : JSON.stringify({ json: forwardedArgs }),
  });

  const text = await res.text();
  return {
    content: [{ type: "text", text }],
    isError: !res.ok,
  };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
